# ============================================================
# app.R — Global Grocery Index Dashboard
# Deploy this file + data/cpi_master_data_final.csv
# to shinyapps.io (or run locally with shiny::runApp())
# ============================================================

library(shiny)
library(shinydashboard)
library(tidyverse)
library(DT)
library(fmsb)

# --- DATA LOADING ---
# The CSV is pre-generated by the scraping scripts in /scraping/finalproj.qmd
# Place it in a /data subfolder alongside this app.R
df <- read.csv("data/cpi_master_data_final.csv", stringsAsFactors = FALSE)
df$unit_price <- as.numeric(gsub(",", ".", df$unit_price))

# Fuzzy category mapping: groups equivalent products across supermarkets
df <- df %>%
  mutate(category = case_when(
    grepl("arroz|rice",           name_raw, ignore.case = TRUE) ~ "Rice",
    grepl("leche|milk",           name_raw, ignore.case = TRUE) ~ "Milk",
    grepl("huevo|egg",            name_raw, ignore.case = TRUE) ~ "Eggs",
    grepl("pollo|chicken",        name_raw, ignore.case = TRUE) ~ "Chicken",
    grepl("pan|bread",            name_raw, ignore.case = TRUE) ~ "Bread",
    TRUE ~ "Other"
  ))

# --- UI ---
ui <- dashboardPage(
  skin = "black",
  dashboardHeader(title = "Global Grocery Index"),

  dashboardSidebar(
    sidebarMenu(
      menuItem("Market Analysis",   tabName = "dashboard", icon = icon("chart-bar")),
      menuItem("Raw Data Explorer", tabName = "data",      icon = icon("table")),
      menuItem("Methodology",       tabName = "info",      icon = icon("microscope"))
    )
  ),

  dashboardBody(
    tags$head(tags$style(HTML(".small-box {height: 110px;}"))),
    tabItems(

      # ── TAB 1: Dashboard ────────────────────────────────────
      tabItem(tabName = "dashboard",
        fluidRow(
          valueBoxOutput("avg_price_box",     width = 3),
          valueBoxOutput("cheapest_store_box",width = 3),
          valueBoxOutput("variation_box",     width = 3),
          valueBoxOutput("total_items_box",   width = 3)
        ),
        fluidRow(
          column(width = 8,
            box(title = "Price Comparison by Supermarket (€)",
                status = "primary", solidHeader = TRUE, width = NULL,
                plotOutput("price_bar_plot", height = "300px")),
            box(title = "Market Pricing Footprint (Radar Analysis)",
                status = "info", solidHeader = TRUE, width = NULL,
                plotOutput("radar_plot", height = "350px"),
                helpText("A smaller shaded area = lower average prices across all categories."))
          ),
          column(width = 4,
            box(title = "Global Filters", status = "warning", solidHeader = TRUE, width = NULL,
                selectInput("cat_filter", "Choose Category:",
                            choices = c("All", sort(unique(df$category)))),
                helpText("Filter to compare the same product category across all three stores.")
            ),
            box(title = "Price Summary Statistics", status = "danger", width = NULL,
                tableOutput("stats_table")),
            infoBox("Data Status", "Pre-scraped CSV", icon = icon("check-circle"),
                    color = "green", width = NULL)
          )
        )
      ),

      # ── TAB 2: Raw Data ─────────────────────────────────────
      tabItem(tabName = "data",
        box(title = "Aggregated Scraper Output", width = 12,
            DTOutput("raw_table"))
      ),

      # ── TAB 3: Methodology ──────────────────────────────────
      tabItem(tabName = "info",
        box(title = "Methodology", width = 12,
            h4("Data Sources"),
            tags$ul(
              tags$li(tags$b("Walmart:"), " Walmart Affiliate API (authenticated via RSA private key)"),
              tags$li(tags$b("Mercadona:"), " tienda.mercadona.es JSON API (robots.txt reviewed)"),
              tags$li(tags$b("DIA:"), " dia.es product pages via rvest HTML scraping")
            ),
            h4("Standardisation"),
            p("All prices converted to EUR using live rates from the Frankfurter API.",
              "US units (oz, lb, gallon) converted to metric (kg, L) for fair comparison."),
            h4("Reproducibility"),
            p("The scraping pipeline lives in ", tags$code("scraping/finalproj.qmd"),
              ". Re-run it locally to regenerate ", tags$code("data/cpi_master_data_final.csv"),
              " and re-deploy.")
        )
      )
    )
  )
)

# --- SERVER ---
server <- function(input, output) {

  filtered_df <- reactive({
    data <- df
    if (input$cat_filter != "All") data <- data %>% filter(category == input$cat_filter)
    data
  })

  # KPI boxes
  output$avg_price_box <- renderValueBox({
    val <- round(mean(filtered_df()$unit_price, na.rm = TRUE), 2)
    valueBox(paste0(val, "€"), "Avg Unit Price", icon = icon("euro-sign"), color = "purple")
  })

  output$cheapest_store_box <- renderValueBox({
    req(nrow(filtered_df()) > 0)
    res <- filtered_df() %>%
      group_by(supermarket) %>%
      summarise(m = mean(unit_price, na.rm = TRUE)) %>%
      arrange(m) %>%
      slice(1)
    valueBox(res$supermarket, "Leader in Value", icon = icon("trophy"), color = "yellow")
  })

  output$variation_box <- renderValueBox({
    req(nrow(filtered_df()) > 1)
    cv <- round(
      (sd(filtered_df()$unit_price, na.rm = TRUE) /
         mean(filtered_df()$unit_price, na.rm = TRUE)) * 100, 1)
    valueBox(paste0(cv, "%"), "Price Volatility (CV)", icon = icon("bolt"), color = "red")
  })

  output$total_items_box <- renderValueBox({
    valueBox(nrow(filtered_df()), "Items Analysed", icon = icon("database"), color = "blue")
  })

  # Bar chart
  output$price_bar_plot <- renderPlot({
    req(nrow(filtered_df()) > 0)
    ggplot(filtered_df(), aes(x = supermarket, y = unit_price, fill = supermarket)) +
      stat_summary(fun = mean, geom = "bar", width = 0.5) +
      stat_summary(fun = mean, geom = "text",
                   aes(label = paste0(round(after_stat(y), 2), "€")),
                   vjust = -0.5, fontface = "bold") +
      theme_minimal() +
      labs(y = "Mean Price (€)", x = NULL) +
      scale_fill_manual(values = c("Mercadona" = "#00a65a",
                                   "DIA"       = "#dd4b39",
                                   "Walmart"   = "#0073b7")) +
      theme(legend.position = "none",
            axis.text.x = element_text(size = 12, face = "bold"))
  })

  # Radar chart
  output$radar_plot <- renderPlot({
    radar_data <- df %>%
      group_by(supermarket, category) %>%
      summarise(avg = mean(unit_price, na.rm = TRUE), .groups = "drop") %>%
      pivot_wider(names_from = category, values_from = avg) %>%
      column_to_rownames("supermarket")

    # fmsb requires max/min rows at the top
    radar_data <- rbind(
      rep(max(df$unit_price, na.rm = TRUE), ncol(radar_data)),
      rep(0, ncol(radar_data)),
      radar_data
    )

    colors_border <- c(rgb(0, 0.65, 0.35, 0.9),
                       rgb(0.86, 0.29, 0.22, 0.9),
                       rgb(0, 0.45, 0.71, 0.9))
    colors_in <- c(rgb(0, 0.65, 0.35, 0.2),
                   rgb(0.86, 0.29, 0.22, 0.2),
                   rgb(0, 0.45, 0.71, 0.2))

    radarchart(radar_data,
               pcol = colors_border, pfcol = colors_in,
               plwd = 4, plty = 1,
               cglcol = "grey", cglty = 1, axislabcol = "grey",
               caxislabels = seq(0, round(max(df$unit_price, na.rm=TRUE)), length.out = 5),
               cglwd = 0.8, vlcex = 1.2)
    legend(x = 1.3, y = 1.0,
           legend = rownames(radar_data[-c(1, 2), ]),
           bty = "n", pch = 20,
           col = colors_border, cex = 1.2, pt.cex = 3)
  })

  # Summary stats table
  output$stats_table <- renderTable({
    filtered_df() %>%
      group_by(supermarket) %>%
      summarise(
        Min = round(min(unit_price, na.rm = TRUE), 2),
        Avg = round(mean(unit_price, na.rm = TRUE), 2),
        Max = round(max(unit_price, na.rm = TRUE), 2)
      )
  }, digits = 2)

  # Raw data table
  output$raw_table <- renderDT({
    datatable(df, options = list(pageLength = 10, scrollX = TRUE))
  })
}

shinyApp(ui, server)
